---
abstract: 'easily copy and compare folders inside tests'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  File::is: 0
  Test::More: 0
  Test::Tester: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
keywords:
  - test
  - dir
  - folder
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Dirs
provides:
  Test::Dirs:
    file: lib/Test/Dirs.pm
    version: 0.01
requires:
  Carp: 0
  File::Copy::Recursive: 0
  File::DirCompare: 0
  File::Temp: 0
  List::MoreUtils: 0
  Test::Builder: 0
  Text::Diff: 0
resources:
  bugtracker: http://github.com/jozef/Test-Dirs/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jozef/Test-Dirs/
version: 0.01
